kumuluzee:
  name: sales
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/SalesDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/sale
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
      web-instrumentation:
        - name: sales-endpoint
          url-pattern: /v1/sales/*
rest-properties:
  external-services:
    order-service:
      enabled: true
