kumuluzee:
  name: sales
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/SalesDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/sale
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/SalesDS
  cors-filter:
    servlet:
      allow-origin: "*"
  streaming:
      kafka:
        consumer:
          bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094
          group-id: group1
          enable-auto-commit: true
          auto-commit-interval-ms: 1000
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          security-protocol: SASL_SSL
          sasl-mechanism: SCRAM-SHA-256
          sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="xtmm0ew0" password="Xq4ZWv7IqtqGroJAJgs45L0GTEbfB3Zv";'
          group-id: newer
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="customers">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="0dd039ba-579f-44fc-b2dc-c5e2bd22b8e9-ls.logit.io" port="23316"
                                                                                             protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'
  metrics:
      web-instrumentation:
        - name: sales-endpoint
          url-pattern: /v1/sales/*
rest-properties:
  external-services:
    order-service:
      enabled: true
  healthy: true
