apiVersion: v1
kind: Service
metadata:
  labels:
    name: node
    role: service
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    grafana: "true"