apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sale-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sale
    spec:
      containers:
      - image: bozen/sale:0.01
        name: sales
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-products:5432/sale
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.20.134:32275
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP