apiVersion: v1
kind: Service
metadata:
  name: sale
  labels:
    app: sale
spec:
  type: NodePort
  ports:
  - name: server
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: sale